<h2 class="hypno">Group by and Aggregation</h2>
<style>
.hypno {
  font-size: 48px;
  text-align: center;
  color: violet;
  animation: hypnoPulse 1s infinite alternate ease-in-out;
}
@keyframes hypnoPulse {
  0% { transform: scale(1); text-shadow: 0 0 5px violet; }
  100% { transform: scale(1.1); text-shadow: 0 0 30px magenta; }
}
</style>

Group by and Aggregation

In [2]:
import pandas as pd
import numpy as np
import random

# Základní možnosti
flavors = [
    "Mint Chocolate Chip", "Chocolate", "Vanilla", "Cookie Dough", "Rocky Road",
    "Pistachio", "Cake Batter", "Neapolitan", "Chocolate Fudge Brownie", "Strawberry",
    "Caramel Swirl", "Mango", "Coffee", "Blueberry", "Butter Pecan"
]
base_flavors = ["Vanilla", "Chocolate"]
liked_options = ["Yes", "No"]

# Generování dat
data = []
for _ in range(50):
    flavor = random.choice(flavors)
    base = random.choice(base_flavors)
    liked = random.choice(liked_options)
    flavor_rating = round(np.random.uniform(2.0, 10.0), 1)
    texture_rating = round(np.random.uniform(2.0, 10.0), 1)
    total_rating = round(flavor_rating + texture_rating, 1)
    data.append([flavor, base, liked, flavor_rating, texture_rating, total_rating])

# Vytvoření DataFrame
df = pd.DataFrame(data, columns=[
    "Flavor", "Base Flavor", "Liked", "Flavor Rating", "Texture Rating", "Total Rating"
])

# Uložení do CSV
df.to_csv("Flavor.csv", index=False)

In [3]:
df=pd.read_csv(r"data\Flavor.csv")
df.head()

         Flavor Base Flavor Liked  Flavor Rating  Texture Rating  Total Rating
0    Strawberry     Vanilla    No            2.0             9.6          11.6
1        Coffee     Vanilla   Yes            9.6             8.5          18.1
2        Coffee   Chocolate   Yes            8.6             6.1          14.7
3     Pistachio     Vanilla   Yes            3.6             7.0          10.6
4  Cookie Dough   Chocolate   Yes            9.8             5.1          14.9

In [ ]:
df. info()  # Zobrazí informace o DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Flavor          50 non-null     object
 1   Base Flavor     50 non-null     object
 2   Liked           50 non-null     object
 3   Flavor Rating   50 non-null     float64
 4   Texture Rating  50 non-null     float64
 5   Total Rating    50 non-null     float64
dtypes: float64(3), object(3)
memory usage: 2.5+ KB

In [ ]:
df.groupby('Base Flavor') #ukaže jaké jsou hodnoty v Base Flavor (text)

In [22]:
grouped= df.groupby('Base Flavor') # pridam grouped, abych mohl použít další funkce

In [23]:
grouped.mean(numeric_only=True)  # Vypočítá průměrné hodnoty pro každou skupinu ....To řekne Pandas, ať ignoruje nečíselné sloupce

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         5.972727        6.654545     12.627273
Vanilla           5.850000        5.792857     11.642857

In [24]:
df.groupby('Base Flavor').count()    #count() spočítá počet řádků v každé skupině (text a čísla)

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate        22     22             22              22            22
Vanilla          28     28             28              28            28

In [ ]:
df.groupby('Base Flavor').min()  # Vypočítá minimální hodnoty pro každou skupinu   Pro Liked , A protože 'No' < 'Yes', vybere No (menší než 'Yes')jako minimální hodnotu.

                   Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Butter Pecan    No            2.3             2.0           4.4
Vanilla         Blueberry    No            2.0             2.5           5.1

In [ ]:
df.groupby('Base Flavor').max() # Vypočítá maximální hodnoty pro každou skupinu  Pro Liked , A protože 'Yes' > 'No', vybere Yes (větší než 'No')jako maximální hodnotu.

              Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Vanilla   Yes            9.8             9.9          18.7
Vanilla      Vanilla   Yes            9.6             9.6          18.1

In [29]:
df.groupby('Base Flavor').sum(numeric_only=True)  # Vypočítá součet hodnot pro každou skupinu (pouze číselné sloupce)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate            131.4           146.4         277.8
Vanilla              163.8           162.2         326.0

In [ ]:
df.groupby('Base Flavor').agg({ 'Flavor Rating': 'mean', 
                               'Texture Rating': 'sum', 
                               'Total Rating': 'max'}) # Vypočítá průměrnou hodnotu 'Flavor Rating', součet 'Texture Rating' a maximální hodnotu 'Total Rating' pro každou skupinu

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         5.972727           146.4          18.7
Vanilla           5.850000           162.2          18.1

In [ ]:
df.groupby('Base Flavor').agg({ 'Flavor Rating': ['mean', 'min', 'max', 'count','sum']})  #  Vypočítá průměr, minimum, maximum, počet a součet 'Flavor Rating' pro každou skupinu

            Flavor Rating
                     mean  min  max count    sum
Base Flavor
Chocolate        5.972727  2.3  9.8    22  131.4
Vanilla          5.850000  2.0  9.6    28  163.8

In [ ]:
df.groupby('Base Flavor').agg({ 'Flavor Rating': ['mean', 'min', 'max', 'count','sum'],
                               'Texture Rating': ['mean', 'min', 'max', 'count','sum'],
                               'Total Rating':['mean', 'min', 'max', 'count','sum']})

            Flavor Rating                        Texture Rating            \
                     mean  min  max count    sum           mean  min  max
Base Flavor
Chocolate        5.972727  2.3  9.8    22  131.4       6.654545  2.0  9.9
Vanilla          5.850000  2.0  9.6    28  163.8       5.792857  2.5  9.6

                         Total Rating
            count    sum         mean  min   max count    sum
Base Flavor
Chocolate      22  146.4    12.627273  4.4  18.7    22  277.8
Vanilla        28  162.2    11.642857  5.1  18.1    28  326.0

In [42]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Strawberry,Vanilla,No,2.0,9.6,11.6
1,Coffee,Vanilla,Yes,9.6,8.5,18.1
2,Coffee,Chocolate,Yes,8.6,6.1,14.7
3,Pistachio,Vanilla,Yes,3.6,7.0,10.6
4,Cookie Dough,Chocolate,Yes,9.8,5.1,14.9
5,Strawberry,Chocolate,Yes,4.2,4.4,8.6
6,Rocky Road,Chocolate,No,6.4,7.8,14.2
7,Caramel Swirl,Vanilla,No,5.4,3.5,8.9
8,Chocolate,Chocolate,No,8.8,9.9,18.7
9,Rocky Road,Vanilla,No,8.2,9.6,17.8
10,Cookie Dough,Vanilla,No,3.2,5.4,8.6
11,Cookie Dough,Chocolate,Yes,3.2,8.1,11.3
12,Blueberry,Vanilla,No,6.2,8.2,14.4
13,Caramel Swirl,Vanilla,No,7.9,6.6,14.5
14,Cake Batter,Vanilla,Yes,7.9,2.9,10.8
15,Mango,Chocolate,Yes,7.7,9.1,16.8
16,Blueberry,Vanilla,Yes,2.3,8.8,11.1
17,Vanilla,Vanilla,No,6.3,7.5,13.8
18,Cake Batter,Vanilla,Yes,6.9,5.9,12.8
19,Chocolate Fudge Brownie,Vanilla,Yes,8.3,3.7,12.0
20,Cookie Dough,Vanilla,No,4.3,4.2,8.5
21,Mint Chocolate Chip,Chocolate,Yes,3.4,5.9,9.3
22,Cake Batter,Chocolate,Yes,6.8,2.1,8.9
23,Vanilla,Chocolate,Yes,4.8,2.0,6.8
24,Pistachio,Chocolate,No,5.8,8.6,14.4
25,Mint Chocolate Chip,Chocolate,No,9.1,3.2,12.3
26,Chocolate,Vanilla,No,6.0,7.3,13.3
27,Strawberry,Vanilla,Yes,2.7,2.5,5.2
28,Cake Batter,Chocolate,No,4.2,8.4,12.6
29,Mango,Chocolate,No,4.4,3.0,7.4
30,Strawberry,Vanilla,Yes,6.7,9.2,15.9
31,Mango,Vanilla,No,9.4,4.2,13.6
32,Pistachio,Chocolate,Yes,2.3,2.1,4.4
33,Neapolitan,Vanilla,Yes,7.4,5.3,12.7
34,Coffee,Vanilla,Yes,3.8,6.2,10.0
35,Caramel Swirl,Chocolate,Yes,8.1,7.4,15.5
36,Rocky Road,Vanilla,No,5.1,6.9,12.0
37,Cookie Dough,Vanilla,No,4.6,3.3,7.9
38,Rocky Road,Vanilla,Yes,5.7,4.2,9.9
39,Neapolitan,Chocolate,Yes,6.6,9.6,16.2
40,Cake Batter,Chocolate,No,5.9,8.9,14.8
41,Strawberry,Vanilla,Yes,2.8,2.6,5.4
42,Caramel Swirl,Vanilla,Yes,9.4,6.7,16.1
43,Cookie Dough,Chocolate,No,4.3,8.9,13.2
44,Mint Chocolate Chip,Vanilla,Yes,2.3,2.8,5.1
45,Butter Pecan,Chocolate,Yes,8.6,6.7,15.3
46,Mango,Vanilla,Yes,8.9,5.2,14.1
47,Rocky Road,Chocolate,No,3.3,9.5,12.8
48,Mint Chocolate Chip,Chocolate,Yes,5.1,9.6,14.7
49,Chocolate Fudge Brownie,Vanilla,No,6.9,4.4,11.3

In [ ]:
df.groupby(['Base Flavor', 'Liked']). mean()   #Ne funguje, protože 'Base Flavor' a 'Liked' je textový sloupec, ale funguje s numerickými sloupci

In [44]:
df.groupby(['Base Flavor', 'Liked']). mean(numeric_only=True)  # Vypočítá průměrné hodnoty pro každou kombinaci 'Base Flavor' a 'Liked'

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   No          5.800000        7.577778     13.377778
            Yes         6.092308        6.015385     12.107692
Vanilla     No          5.807692        6.207692     12.015385
            Yes         5.886667        5.433333     11.320000

In [45]:
df.groupby(['Base Flavor', 'Liked']).agg({ 'Flavor Rating': ['mean', 'min', 'max', 'count','sum']})

                  Flavor Rating
                           mean  min  max count   sum
Base Flavor Liked
Chocolate   No         5.800000  3.3  9.1     9  52.2
            Yes        6.092308  2.3  9.8    13  79.2
Vanilla     No         5.807692  2.0  9.4    13  75.5
            Yes        5.886667  2.3  9.6    15  88.3

In [46]:
df.groupby('Base Flavor').describe()  # Vypíše základní statistiky pro každou skupinu (průměr, minimum, maximum, atd.)

            Flavor Rating                                                  \
                    count      mean       std  min    25%   50%  75%  max
Base Flavor
Chocolate            22.0  5.972727  2.221793  2.3  4.225  5.85  8.0  9.8
Vanilla              28.0  5.850000  2.391884  2.0  3.750  6.10  7.9  9.6

            Texture Rating            ...            Total Rating             \
                     count      mean  ...   75%  max        count       mean
Base Flavor                           ...
Chocolate             22.0  6.654545  ...  8.90  9.9         22.0  12.627273
Vanilla               28.0  5.792857  ...  7.35  9.6         28.0  11.642857


                  std  min   25%   50%     75%   max
Base Flavor
Chocolate    3.644459  4.4  9.80  13.7  14.875  18.7
Vanilla      3.470770  5.1  9.65  11.8  13.875  18.1

[2 rows x 24 columns]